apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aub-advisor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamadbazzy/Agentic_Rag.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: aub-advisor-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true