apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: agentic-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-output-pvc
  namespace: agentic-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 