apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-job
  namespace: agentic-rag
spec:
  template:
    spec:
      containers:
      - name: scraper
        image: miriamcs/agentic-rag-scraper:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "scrape.py", "--output-dir", "/app/Scraper/output"]
        volumeMounts:
        - name: scraper-output
          mountPath: /app/Scraper/output
        - name: scraper-logs
          mountPath: /app/logs
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "150m"
            memory: "256Mi"
      volumes:
      - name: scraper-output
        persistentVolumeClaim:
          claimName: scraper-output-pvc
      - name: scraper-logs
        emptyDir: {}
      restartPolicy: OnFailure 