version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Beirut  # Set to your timezone 